CREATE TABLE IF NOT EXISTS DISCORD_BOT_LEAGUE (
    PUUID varchar(78) PRIMARY KEY,
    CREATED_AT date NOT NULL,
    DELETED_AT date,
    FLEX_DIVISION varchar(20),
    FLEX_RANK int,
    FLEX_POINTS int,
    SOLO_DIVISION varchar(20),
    SOLO_RANK int,
    SOLO_POINTS int,
    UPDATED_AT timestamp
);

CREATE TABLE IF NOT EXISTS DISCORD_BOT_LEAGUE_PHRASES (
    ID SERIAL PRIMARY KEY,
    SENTIMENT boolean NOT NULL,
    PHRASE varchar NOT NULL
);